### ISSUE TITLE
Extend DAIA by loan statistics

### ISSUE THREAD

**Issue by nichtich** [nichtich/ideas#16]
[DAIA](http://gbv.github.io/daia/) only allows to query the current availability of a document (or its exemplar) in a library. Loan history and/or frequencies would require another data format or extension of DAIA specification. 

The data could be provided as data feed simimlar to [CrossRef Event Data](https://www.crossref.org/services/event-data/).

### Resources

* LBS OUS provides some loan statistics for individual books (not publically available, see <https://twitter.com/vform/status/1059789641107324928>)

* Some libraries have [published loan data dumps](https://toolbox.google.com/datasetsearch/search?query=library%20loan)

### Tasks

* [ ] Sketch/implement a use case what to do with the data
* [ ] Find a library that wants to process/publish loan data
* [ ] Create data format and map/publish existing loan data
